### ISSUE TITLE
Unable to invoke Debugger

### ISSUE THREAD

**Issue by scottdillon1** [SAP-samples/cloud-cap-nodejs-codejam#15] opened 2019-10-31 02:29 UTC
As part of the exercises, we are asked to run the VS Code debugger but when I try to do that, I receive the following error.

![VSDebug](https://user-images.githubusercontent.com/38572368/67913850-bbf1d400-fb64-11e9-93cd-91d4d347794f.jpg)

**Comment by socenmarc** [comment] 2019-11-05 22:29
Hi @scottdillon1,
I get the same error. Did you solve it?

Thanks in advance,
Marc

**Comment by scottdillon1** [comment] 2019-11-05 23:53
Hi Marc, glad to know it’s not just me...unfortunately I have not solved it.

What do you do for SAP?

Scott Dillon
NA Centre of Excellence
SAP Cloud Platform
SAP Canada

Mobile (613) 799-8924
Office (613) 364-2598

Register for our new series “In the SCP Garage with yours truly”...monthly series designed to bring your targeted information in an informal setting...
https://event.on24.com/eventRegistration/EventLobbyServlet?target=reg20.jsp&partnerref=SD&referrer=&eventid=1757313&sessionid=1&key=409EFCD37FA19BF0BECF0132A02020CA&regTag=311279&sourcepage=register

On Nov 5, 2019, at 5:29 PM, Marc Maurí <notifications@github.com> wrote:

﻿

Hi @scottdillon1<https://github.com/scottdillon1>,
I get the same error. Did you solve it?

Thanks in advance,
Marc

**Comment by DusanSacha** [comment] 2019-11-07 14:45
@scottdillon1 @socenmarc 
I had the same problem and found out this could be caused by having spaces in your node path installation on Windows.
e.g. C:\Program Files\nodejs

I updated my nodejs to the latest version + installed it into another path (without spaces) and from now on I can use debugger as in the exercises.

**Comment by socenmarc** [comment] 2019-11-12 16:23
Hi @DusanSacha, thanks for answering.

Another option:
- Create a new file `cds.js` in the `.vscode` directory
- In the new file `cds.js`, add the following code:

> // used in launch.json to refer to an installed cds via an absolute path
> const cds = require('@sap/cds')
> cds.exec()

- In `.vscode` directory, replace `launch.json` code with:

> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>       {
>         "name": "cds run",
>         "type": "node",
>         "request": "launch",
>         "program": "${workspaceFolder}/.vscode/cds",
>         "args": [
>           "run"
>         ],
>         "skipFiles": [
>           "<node_internals>/**/*.js",
>           "**/cds-reflect/lib/index.js",
>           "**/cds/lib/index.js",
>           "**/.vscode/cds.js"
>         ],
>         "autoAttachChildProcesses": true,
>         "console": "integratedTerminal"
>       }
>     ]
> }

That works for me.

Regards,
Marc

**Comment by chgeo** [comment] 2019-11-19 20:24
For new projects, this will be fixed by `@sap/cds` 3.20.0 tomorrow.

**Comment by usherfu** [comment] 2019-12-02 09:38
Is there any example/ guidance how to setup the launch.json for debug?  I am facing the same issue.

**Comment by IObert** [comment] 2019-12-02 09:54
I just created a new project with `cds 3.20.1` and this is the `launch.json` I got generated:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "cds run",
      "type": "node",
      "request": "launch",
      "program": "${workspaceFolder}/.vscode/cds",
      "args": [ "run", "--with-mocks", "--in-memory?" ],
      "skipFiles": [ "<node_internals>/**" ],
      "console": "integratedTerminal",
      "autoAttachChildProcesses": true
    }
  ]
}
```
and `cds.js` in the same directory:
```
// used in launch.json to refer to an installed cds via an absolute path

const cds = require('@sap/cds');
cds.exec();
```

I hope this helps

**Comment by usherfu** [comment] 2019-12-02 09:55
In case it helps, following worked for me

In launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cds run",
            "request": "launch",
            "type": "node", "runtimeExecutable": "npx","runtimeArgs": [ "-n" ],
            "args": [ "--","cds","run", "--in-memory" ], // the leading "--" arg ensures it works with as well as without debugging
            "cwd": "${workspaceFolder}/packages/bookstore",    
            "console": "integratedTerminal",
            "skipFiles": [ "<node_internals>/**" ]
        }
    ]
}

**Comment by IObert** [comment] 2019-12-02 09:59
Great!

I'll close this issue now, as it seems to be resolved. Please reopen if needed.

**Closed as completed by IObert** 2019-12-02 09:59 UTC

**Comment by rocantonio** [comment] 2020-04-20 14:40
Hi all, still having issues with the new debug **launch.json**. I can run "cds run" with no problems in a terminal but when I run these on VSCode Debuger that happens:
![image](https://user-images.githubusercontent.com/13656734/79764266-6cc37980-8325-11ea-9616-f40789eb42a7.png)

I really need help on that.

**Comment by chgeo** [comment] 2020-04-20 14:56
This looks like you run an old Node.js version.  Should be version 10 minimum.
Check with `node --version`.
